### PR TITLE
cover updates

### PR DESCRIPTION
**Pull request by dantob**
I went with 512x650 for most covers, it was close to what a majority already were and 512x512 for the jewel case ones

### CODE REVIEW

**Comment by RobLoach** [comment]
Is it just me, or does this look squished?
## Original
.png)
## New
.png)

**Comment by dantob** [comment]
I was trying to make them a consistent size, but it definitely does. I think I'm just gonna leave them how they are, and we'll just set a 512px width limit, which is pretty much what they already are. I'll change this pull for the new art only

**Comment by RobLoach** [comment]
These look much better! Thanks a lot. Think they're good to go?

**Comment by dantob** [comment]
The only thing to note, is that the doom II cover is mirrored to what we had before, it seems like it was a custom 'fan made' version. I can't find any other references to it

**Pull request merged**
